name: comdig
description: The COMDIG App in Flutter.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  flutter_secure_storage: ^8.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  bloc_test: ^9.1.1
  mask_text_input_formatter: ^2.4.0
  dio: ^5.0.1
  http: ^0.13.5
  pretty_dio_logger: ^1.1.1
  go_router: ^6.2.0
  mocktail: ^0.3.0
  dart_jsonwebtoken: ^2.7.1
  get_it: ^7.2.0
  jwt_decode: 0.3.1
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  icons_plus: ^4.0.0
  lottie: ^2.7.0
  html: ^0.15.4
  image_picker: ^1.0.4
  mime: ^1.0.4
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
